apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-deployment
  labels:
    app: menu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu
  template:
    metadata:
      labels:
        app: menu
    spec:
      containers:
      - name: menu
        image: menu:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: myacrcredentials 
---
apiVersion: v1
kind: Service
metadata:
  name: menusvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: menu